### ISSUE TITLE
How to allocate permission?

### ISSUE THREAD

**Issue by 40lsgy1** [rcosnita/eCommerce-RBAC#1]
Hi, rcosnita.

I read [Scenario-1-small-businesses](https://github.com/rcosnita/eCommerce-RBAC/wiki/Scenario-1-small-businesses) in your wiki.

In that case, if role customer support and marketing both have the permission "view report", they can "view all reports" in their company. 

But how to redesign the erd to make it possible that both role can noly "view report" in their department or created by themselves.

**Comment by rcosnita** [comment]
Hi ABJ351R7,

This will not work out of the box but it is fairly easy to implement it. You create a permission named "view report from my deparment". Then, at api / service level where reports are accessed (e.g: /reports/5) you put some custom code:

if (user has permission "view report from my department" and report.department == user.department) {
     // show report
} else {
    throw new ForbiddenException();
}

I hope it helps,
Radu
