### ISSUE TITLE
Separation of Duty

### ISSUE THREAD

**Issue by ancgate** [rcosnita/eCommerce-RBAC#4]
Hi rcosnita, again this is a great chez d'oeuvre. I would like to know how you will be able to manage the Dynamic Separation of Duty during authentication. When the user login as customer service and supervisor also, I make a union of the list of permissions. How do I check the DSD or the SSD? If possible, can you provide an example? 

Thanks

**Comment by rcosnita** [comment]
Hi @ancgate,

During authentication I think you don't have to check any of the permissions. During authorization phase you should decide what permissions to activate.

Let's take the example you provided which I think is a very good one:

## Solution (assuming you don't want a supervisor to have it's permissions activated all the time)

You can activate only the permissions for the customer service initially. Then, your client app should ask the authorization server (or might decide based on the information received during authorization) if the user is also a supervisor. In case it is, you should have a dedicated endpoint in the authorization privileges which can temporary elevate user permissions (I recommend you do this in a generic manner). Doing it like this will allow you to extends the whole process in the future (e.g verification using some sort of MFA). This is where you can enforce the DSD.

Does the answer help?

**Comment by ancgate** [comment]
Yes, it helps and I think I can work this out. Thank you. By the way, I don't why, but the Visual Paradigm File is not opening. I will create another issue for that.
