### ISSUE TITLE
Visual Paradigm File is corrupted.

### ISSUE THREAD

**Issue by ancgate** [rcosnita/eCommerce-RBAC#5]
I can't open Visual Paradigm. Whenever I opened it got the error in the images below. I'm using the version 12.1 on a mac. 
<img width="1002" alt="screen shot 2018-08-29 at 17 29 07" src="https://user-images.githubusercontent.com/4063982/44816967-e38c8b80-abb1-11e8-9e25-6501a7898260.png">
<img width="1128" alt="screen shot 2018-08-29 at 17 30 13" src="https://user-images.githubusercontent.com/4063982/44816968-e38c8b80-abb1-11e8-805e-4c4d5063b346.png">

**Comment by rcosnita** [comment]
I did not edit this file in a long time. Probably, a version from 2 or 3 years ago will fix the problem.

**Comment by ancgate** [comment]
I have opened it with Visual Paradigm 9. It was very hard to find that one. Thanks
